### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by jimidle** [marcojakob/dart-makery-ui-tree-view#3]
I can't get this to work (Dart 1.16.0 - Polymer 1.0.0-rc.16) and it seems that it is no longer maintained. Perhaps it would be kinder to delete the project so that people do not waste time trying to use it, then realize that it is probably too old to use.

Or perhaps you want to bring it up to date and publish it? There appears to be no solutions out there for trees based on polymer dart.

**Comment by marcojakob** [comment]
Yes, I haven't used it in a while and Polymer has changed quite a bit since (but, well, Polymer Dart 1.0 is still not released...).

If you want to update it for the current Polymer version I'd be happy to accept pull requests. I have a few other projects that I need to keep updated and won't have much time for this one.
